add port as variable and fix paths
lsst-dm/s3daemon pull request #6
Opened 2023-12-20 12:37 UTC by csilva-cl

- s3daemon port can be changed but defaults to 15555
- some path fixes
- add support text when doing repeats of transfers

2023-12-20 17:13 UTC, womullan commented on summittests/sendTest.sh
> +repeat=2
i switched away from this to total files - the number of files is not the same on each machine so if you use repeat the stats. So this change will mess up the plots when you run for large numbers.
It is better to state 200 files not reapet x files 10 times where you do not know what x is ..

2023-12-20 17:13 UTC, womullan requested changes
ok except the repeat ..

2023-12-21 04:30 UTC, ktlim commented on python/s3daemon/s3daemon.py
> +PORT = int(os.environ["S3DAEMON_PORT"])
If you want the port to truly default to 15555 even if nothing is specified, this can be:
```
PORT = int(os.environ.get("S3DAEMON_PORT", 15555))
```

2023-12-21 04:31 UTC, ktlim commented
I'm fine with the port env var.

2024-09-06 18:10 UTC, womullan commented
@csilva-cl I think you can close this now - Josh has the ports and as I explained the other is not good

2024-09-06 18:11 UTC, womullan commented
@csilva-cl perhaps close - obsoloete now ?

2024-09-06 19:41 UTC, csilva-cl commented
obsolete

2024-09-06 19:41 UTC, closed without merging